module.exports = {
  //these fields were provided by the github issue these are the default values I am assuming
  type: 'friend',
  host: 'dynamic',
  context: 'authenticated',
  dtmfMode: 'auto',
  directMedia: 'no',
  nat: 'force_rport,comedia',
  disallow: 'all',
  allow: 'g722:20;ulaw:20;h264:20',
  insecure: 'no',
  progressInBand: 'never',
  videoSupport: 'yes',
  maxCallBitrate: '384',
  qualify: 'no',
  qualifyFreq: '60',
  encryption: 'no',
  keepAlive: 'no',
  directrtpSetup: 'no',
  trustIdOutbound: 'legacy',
  ciscoUseCallManager: 'no',
  lastms: null,
  port: 0,
  permit: '',
  transport: 'udp,tcp,tls,ws,wss',
  language: '',
  trustrpid: '',
  sendrpid: '',
  rtpkeepalive: 0,
  outboundproxy: '',

  //these columns are not nullable with no default (required)
  deny: '',
  canReinvite: '',
  dtlscertfile: '',
  dtlsprivatekey: '',
  dtlscafile: '',
};
