module.exports = {
  pager: '',
  attach: 'yes',
  welcomeoption: 'Auto',
  tz: 'America/Chicago',
  tzbytenant: 'on',
  deleteVoicemail: 'yes',
  language: '',
  maxmsg: '50',
  exitcontext: 'voicemailOperator',
  operator: '',
  minsecs: '2',
  envelope: 'yes',
  saycid: '',
  review: '',
  maxsecs: '120',
  transcriptStore: '',
  category: '',
  onnewmessageparam1: '',
  onnewmessageparam2: '',
  onnewmessageparam3: '',
  ivrId: 0,
};
