const Joi = require('joi');
const RULES = require('./rules');

const schema = Joi.object().keys({
  extType: RULES.EXTTYPE,
  extNumber: RULES.EXTNUMBER,
  extName: RULES.EXTNAME,
  location: RULES.LOCATION,
  branch: RULES.BRANCH,
  department: RULES.DEPARTMENT,
  cidNums: RULES.CIDNUMS,
  cidNum: RULES.CIDNUM,
  sipPass: RULES.SIPPASS,
  sipUser: RULES.SIPUSER,
  callLimit: RULES.CALLLIMIT,
  existingDevice: RULES.EXISTINGDEVICE,
  newDevice: RULES.NEWDEVICE,
  tenantCode: RULES.TENANTCODE,
  tenantId: RULES.TENANTId,
  email: RULES.EMAIL,
  fmfmDialMethod: RULES.FMFMDIALMETHOD,
  fmfmNumber: RULES.FMFMNUMBER,
  followMe: RULES.FOLLOWME,
  prefix: RULES.PREFIX,
  recording: RULES.RECORDING,
  sendInvite: RULES.SENDINVITE,
  unconditionalStatus: RULES.UNCONDITIONALSTATUS,
  voicemailDelivery: RULES.VOICEMAILDELIVERY,
});

const updateSchema = Joi.object().keys({
  branch: RULES.BRANCH,
  callLimit: RULES.CALLLIMIT,
  cidNum: RULES.CIDNUM,
  cidNums: RULES.CIDNUMS,
  cidNumsChanged: RULES.CIDNUMSCHANGED,
  department: RULES.DEPARTMENT,
  device: RULES.UPDATEDEVICE,
  deviceType: RULES.DEVICETYPE,
  dialTimeout: RULES.DIALTIMEOUT,
  dnd: RULES.DND,
  email: RULES.EMAIL,
  emergencyCidNum: RULES.EMERGENCYCIDNUM,
  existingDevice: RULES.UPDATEEXISTINGDEVICE,
  extBusy: RULES.UPDATEEXTDST,
  extHasDevice: RULES.EXTHASDEVICE,
  extName: RULES.EXTNAME,
  extNoAnswer: RULES.UPDATEEXTDST,
  extNumber: RULES.EXTNUMBER,
  extOffline: RULES.UPDATEEXTDST,
  extType: RULES.EXTTYPE,
  fmfmDialMethod: RULES.FMFMDIALMETHOD,
  fmfmNumber: RULES.FMFMNUMBER,
  fmfmStatus: RULES.FMFMSTATUS,
  forwardingDestType: RULES.FORWARDINGDESTTYPE,
  forwardingDestination: RULES.FORWARDINGDESTINATION,
  muId: RULES.MUID,
  newDevice: RULES.UPDATENEWDEVICE,
  prefix: RULES.PREFIX,
  recording: RULES.RECORDING,
  removeDevice: RULES.REMOVEDEVICE,
  sendInvite: RULES.SENDINVITE,
  tenantId: RULES.TENANTId,
  unconditionalStatus: RULES.UNCONDITIONALSTATUS,
  followMe: RULES.FOLLOWME,
});

const joiOptions = { convert: true, abortEarly: false };

module.exports = { updateSchema, schema, joiOptions };
